### ISSUE TITLE
Relevance of NoUncurriedPrefix

### ISSUE THREAD

**Issue by stil4m** [stil4m/elm-analyse#20]
The `NoUncurriedPrefix` checks if binary operators are used in prefix notation instead of infix notation. For example: `(+) 1 2` instead of `1 + 2`.

Sometimes using operator prefix notation is more convenient.

To construct tuples (@manuscrypt):

```
[ (,) "color" "red" ]
```

Or for [elm-css](package.elm-lang.org/packages/rtfeldman/elm-css/latest):

```
(.) MyClass
    [ ...
    ]
```

The point is:
Should this check be dropped, become less strict, highly configurable or something else?
Suggestions are welcome :)

**Comment by zwilias** [comment]
I'm a bit torn on this. The two use cases presented here both have alternatives - `(=>)` from [rocket update](http://package.elm-lang.org/packages/NoRedInk/rocket-update/latest) for a more convenient tuple syntax, and `class` for elm-css. So I'd stick with having the NoUncurriedPrefix rule on by default, and open up the discussion again if/when it turns out people would rather have it be more configurable.

**Comment by stil4m** [comment]
If you want you can disable the check using a `elm-analyse.json` configuration file.

**Comment by lydell** [comment]
(Note that elm-css uses `class MyClass []` now.)

**Comment by stil4m** [comment]
`FunctionsInLet` enabled by default seems a good default. Closing this.
