### ISSUE TITLE
Integrating into vscode extension

### ISSUE THREAD

**Issue by hakonrossebo** [stil4m/elm-analyse#77]
Hi, I think this is a great tool - thank you for creating it :)

I've been doing some work on vscode-elm lately and I'm considering adding a command to run elm-analylse. Has there been any attempts to do this in other editors? If this seems ok, it may also be possible to have a setting to run elm-analyse together with the linter, enabling warnings/green lines in the editor.

Also - is there any setting to enable json output?

**Comment by stil4m** [comment]
@hakonrossebo :).

I already thought about this a bit. The first step into this is [Issue 74](https://github.com/stil4m/elm-analyse/issues/74). 

Elm analyse currently hosts a websocket in server mode and I already experimented with an Atom plugin that will show the linted messages. In under 100 lines of JS this works in Atom (and #74 still has to be resolved).

The important part is that the interface is well. If you can do some research, agnostic from elm-analyse, what data/information you need to get the VSCode messages up and running. Then afterwards we can do some knowledge sharing to come up with a good API that will scale to a broader group of editors.

**Comment by hakonrossebo** [comment]
Ok. for the multiple editor API, I've been looking into how we can specify the requirements for a common language server for Elm by implementing the [Common Language server protocol](https://code.visualstudio.com/blogs/2016/06/27/common-language-protocol). Maybe elm-analyse could implement the [publishDiagnostics](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_publishDiagnostics) message? This would expose a [diagnostic collection](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#diagnostic). This is exactly the same diagnostics information vscode uses. I think this should cover most other [editors](https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations)

**Comment by hakonrossebo** [comment]
As mentioned in the referenced issue from vscode-elm, I've done a simple test PR to see how we can view diagnostic info in vscode. I don't know how much you know vscode extensions, but it's quite easy to test - just clone PR, npm install and open project in vscode. Press debug/F5 to launch a separate vscode extension development instance.

**Comment by stil4m** [comment]
Cool. I've looked at the code.

I see you did some work to fix the ranges (start and end). Since you played around with this I have one question on this:

* How are the ranges structured? Currently it seems that the rows and columns are 1-based (not starting with zero). Is this true?

My plan is to expose all the ranges normalized as zero based and containing no negative numbers. This would imply that for VSCode all values just have to be incremented by `1`.

I see you started the `elm-analyse` process and then parse the output.

My preference goes to using the `elm-analyse -s` feature that will run it as a server. Then the add-on could just open a websocket to listen to the analysis `state`. This contains all the messages and other stuff. I've started with an equal implementation for Atom found [here](https://github.com/stil4m/atom-linter-elm-analyse/blob/master/client.js). The interesting part is `client.js`. This is still heavily WIP, thus nothing is sure yet. [Here](https://github.com/stil4m/atom-linter-elm-analyse/blob/master/index.js#L15) you see the same struggle with ranges you had, thus you see the importance of #74. In that add-on I just start elm-analyse manually.

The 0.9.0 version of elm-analyse will reanalyse a file when it is saved, and push a new state on the websocket. Thus no work is required in the plugin besides listening to the state and updating the editor.

For now I just gonna work on #74 and let you know when that rounds up.

**Comment by hakonrossebo** [comment]
According to [documentation](https://code.visualstudio.com/docs/extensionAPI/vscode-api#Position) positions should be zero based. I think zero based is ok, and then let each editor extension handle differences.

I only did the simple process stdout parsing now, but yes, I think the server approach with separate handling for file updates seems like a better approach. I'll try to test this approach. What are your thougths on the LSP way of providing a server? https://code.visualstudio.com/docs/extensions/example-language-server

**Comment by stil4m** [comment]
I think LSP would be a future step. A coherent solution from the community would be a good option. I do not think building this from an `elm-analyse` perspective is a good idea. It would be better if this is launched from a core team. If this project, and/or the ideas, is then be adopted it would make me a happy developer. In the mean time we should investigate its purposes and where it can be applied.

Today I already refactored the ranges. Currently the messages contain a normalised range. Documentation of the format still needs to be realised. The websocket path changed from `/dashboard` to `/state` in #74.

**Comment by stil4m** [comment]
Just released 0.9.0. Next step is #82. This will include how you can integrate from VSC.

**Comment by hakonrossebo** [comment]
Thanks. I've updated my PR to use websockets and v0.91.

My PR is very unstable now. It does seem to retrieve the initial messages, but it does not seem to work when a file is modified (does not seem to send messages).
I'm also starting elm-analyse as a process inside vscode (also tried in a separate console) and it seems to use a lot of processing/memory. The console output seems to re-load files from eml-stuff\.elm-analyse

![image](https://user-images.githubusercontent.com/367175/27323267-42031872-55a1-11e7-8070-11823aac5c99.png)
I've tried to run as a separate console, with an exclude config for elm-stuff, but it seems to be the same.

After the initial messages, I seem to get some websocket related errors from elm-analyse (trying to send when closed) but I'm not sure if this could be related to my ws implementation - have not used ws before. 

For the API, I'm processing the message (https://github.com/Krzysztof-Cieslak/vscode-elm/pull/145/files#diff-ef247f7191f7288a9ab90f163005c501) to fetch src/range and it seems a bit difficult to fetch the type first, then fetch the object based on the type name. Is it possible to have the message to adopt a json structure like this? https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#diagnostic

Also, by the language server implementation, I did not mean that you should create a full language server, but that elm-analyse could expose it's diagnostics using the same json-rpc protocol and message structure.  I don't know too much about this - just thinking :)

**Comment by stil4m** [comment]
`elm-analyse` should not reload files in the `.elm-analyse` directory. This seems like a bug. Can you create a separate issue for this? As I  hope not, this may be Windows issue :/.

As shown in my Atom example. To receive the state, first a `ping` message needs to be send.

As for the API. The diagnostics are an abstraction on the messages. And as far as I understand a diagnostic applies to a single range in a file. Messages can apply on multiple (a is overridden by b). This means messages to diagnostics have at least a one-to-many relation, or maybe a many-to-many relation. Im not sure yet. Thus I want to stall this a bit.

Since the project is still very `0.X.X` version based I would like to fix things incrementally. As I see it, at least documentation is required (including the API for the *none* language server format). In the future the language server format is likely be supported. But if I build it and expose it, it also needs to be maintained. If it is heavily used, I want to heavily think about it before I create it ;).

**Comment by hakonrossebo** [comment]
Verified linux and created #83

**Comment by hakonrossebo** [comment]
As for API design and this project - I agree that it's better to hurry slowly - no need to rush :)

**Comment by stil4m** [comment]
@hakonrossebo In the new version of Elm analyse I'm planning to change a few things. I've got a working implementation for Atom that connects to elm-analyse via a websocket which makes code like [this](https://github.com/Krzysztof-Cieslak/vscode-elm/blob/73913e7019a03e0bc41e7cb9b74401872990959f/src/elmAnalyse.ts#L32) obsolete. Are you still interested in maintaining the VS code integration of elm-analyse? If not, I will probably pick it up myself (in the future). But if so, maybe we can try to get the VS code integration working with the upcoming version of elm-analyse (0.13)

**Comment by stil4m** [comment]
I'll close this since the VSCode integration is working.
