### ISSUE TITLE
Slower check times with 0.8.0

### ISSUE THREAD

**Issue by Ruudieboy** [stil4m/elm-analyse#78]
I noticed the check times are considerably longer with 0.8.0

For instance with 0.7.0 checking all my files took 35 seconds (including running elm-package install)
With 0.8.0 this takes 74 seconds. 
I cleaned my elm-stuff directory before both runs.

**Comment by stil4m** [comment]
I've did a small test:

|       | Clean | Only parse source
| ---   | ---   |  ---  |
| 0.7.0 |   43s  | 20s
| 0.8.0 |   78s  | 20s

It seems that indexing the dependencies results in the drop of performance (around 35s).
This is probably due to a mechanism introduced for #68.

Further research is required

**Comment by stil4m** [comment]
The main improvement made here is that the interfaces for each dependency will now be stored in your home dir. This will also allow the computed interfaces to be reused for other projects.
For now I leave it with as this for the 0.9.0 version.
